### ISSUE TITLE
Node Red instance link to Node Red Web Editor is broken.

### ISSUE THREAD

**Issue by dekatWin** [ioBroker/ioBroker.node-red#324]
If you enable Node Red's https(ssl) encryption, the instance button hyperlink to node Red Web Editor no longer works. 

Clicking on the instance button under the node Red instance opens a new node Red Web Editor link in the browser with http instead of https, which causes the browser unable to find anything under the hyperlink.

![Screenshot 2022-08-20 23 33 01](https://user-images.githubusercontent.com/111662370/185766751-c2f504f1-6555-4d74-94d7-c5420fe2252a.png)

**Comment by dekatWin** [comment]
![image](https://user-images.githubusercontent.com/111662370/205493926-8777f686-eb23-43fa-904c-a11bac6b671b.png)

**Comment by Apollon77** [comment]
WHich URL is in the link? The correct one or an wrong one?

**Comment by dekatWin** [comment]
the wrong one:

Currently it is always:
 http://192.XXX.XXX.XX:XXXX/ 

But it should look like this:
 https://192.XXX.XXX.XX:XXXX/ 

If you activate https for Node Red.

**Comment by dekatWin** [comment]
As soon as you set https, the link in the overview is also broken. 
So every NodeRed link inside the admin adapter is broken, except the internal view, once you set https.

Also, why is the post here actually marked as a question, its a bug.
![Screenshot 2023-02-14 05 29 32](https://user-images.githubusercontent.com/111662370/218641120-ad8cf593-2927-4aee-b475-235f4a16e3a4.png)

**Comment by dekatWin** [comment]
thx.

**Comment by dekatWin** [comment]
Its fixed now, thank you.

**Comment by Deeds87** [comment]
This bug is not fixed for me.
After changeing to https the link to the web editor ist httpundefined://ip-address:port. 
If i change back to http the link won't be updated and is still broken.
Every new instancace of the adapter has this issue too. Even without changeing anything.
