### ISSUE TITLE
Node-red has an invalid jsonConfig

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.node-red#433]
With the current version of Node-RED (5.1.0), I am getting the following error when I access the instance settings:

`
admin.0 | 2024-01-31 09:16:12.801 | warn | node-red has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"iconPosition"},"message":"must NOT have additional properties"}]
`

Is there a connection to the following [issue](https://github.com/ioBroker/ioBroker.admin/issues/2184)?

**Comment by klein0r** [comment]
See https://github.com/ioBroker/adapter-react-v5/issues/266

**Comment by mcm1957** [comment]
@mickym2 
according to https://github.com/ioBroker/adapter-react-v5/issues/266 this issue should be solved.
Please verify

**Comment by mickym2** [comment]
See my last comment in this referred link. It isn't solved. 
Here just verified again:

![image](https://github.com/user-attachments/assets/e9ad0898-4f82-4160-a382-6ff92cfd6182)

`node-red has an invalid jsonConfig: [{"instancePath":"/items/_authentication/items/authExt/items/2","schemaPath":"#/items/allOf/36/then/allOf/1/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"width"},"message":"must NOT have additional properties"},{"instancePath":"/items/_authentication/items/authExt","schemaPath":"#/patternProperties/%5E.%2B/allOf/25/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/_authentication","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

**Comment by mcm1957** [comment]
THIS Issue reports the following error:
```
admin.0 | 2024-01-31 09:16:12.801 | warn | node-red has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"iconPosition"},"message":"must NOT have additional properties"}]
```

You refer to ANOTHER warning . most likely the rror you logged here: https://github.com/ioBroker/ioBroker.node-red/issues/458

As your current log does NOT show THIS error, I saaume that it is really fixed and this issue can be closed.

**Comment by mickym2** [comment]
Yes . I refer to this error and this issue - and there is also a link that this is solved which isnt. https://github.com/ioBroker/ioBroker.node-red/issues/458

And my original post in the forum refers to this issue and for me it looks the same as it throws an error that the jsonConfig of the NodeRed Adapter is invalid. The config is different and the details of the error is different, but for me as user or in general this adapter problem exists since the adapter was update in March this year. 

I do not know, what should I report???? - The log above is 20 minutes old and the warning is Node-red has an invalid json-Config. So why is this solved????

**Comment by pafade89** [comment]
I haven't had any errors in the log since the following versions.

Node-Red: 5.2.1
Admin 7.0.23
Controller: 6.0.11

Of course, this only pertains to the error mentioned:

`admin.0 | 2024-01-31 09:16:12.801 | warn | node-red has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"iconPosition"},"message":"must NOT have additional properties"}]`
